export const SERVER = {
  BASE: `${import.meta.env.VITE_BASE_URL}`,
  AUTH: `${import.meta.env.VITE_AUTH_URL}`,
  ADMIN: `${import.meta.env.VITE_ADMIN_URL}`,
  USER_AVATAR: `${import.meta.env.VITE_USER_AVATAR_URL}`,
  USER_PROFILE: `${import.meta.env.VITE_USER_PROFILE_URL}`,
  USER_CART: `${import.meta.env.VITE_USER_CART_URL}`,
  USER_ADDRESS: `${import.meta.env.VITE_USER_ADDRESS_URL}`,
  MATERIALS: `${import.meta.env.VITE_MATERIALS_URL}`,
  SHIRTS_MATERIALS: `${import.meta.env.VITE_SHIRTS_MATERIALS_URL}`,
  POLO_SHIRTS_MATERIALS: `${import.meta.env.VITE_POLO_SHIRTS_MATERIALS_URL}`,
  COATS_MATERIALS: `${import.meta.env.VITE_COATS_MATERIALS_URL}`,
  OVERCOATS_MATERIALS: `${import.meta.env.VITE_OVERCOATS_MATERIALS_URL}`,
  PANTS_MATERIALS: `${import.meta.env.VITE_PANTS_MATERIALS_URL}`,
  JEANS_MATERIALS: `${import.meta.env.VITE_JENAS_MATERIALS_URL}`,
  CHINOS_MATERIALS: `${import.meta.env.VITE_CHINOS_MATERIALS_URL}`,
};
